In [1]:
import gzip
import os

import numpy as np
import correctionlib

os.chdir("/work/mmarcheg/PocketCoffea")

from parameters.pileup import pileupJSONfiles
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

In [2]:
pileupJSONfiles

{'2016_PreVFP': {'file': '/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2016preVFP_UL/puWeights.json.gz',
  'name': 'Collisions16_UltraLegacy_goldenJSON'},
 '2016_PostVFP': {'file': '/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2016postVFP_UL/puWeights.json.gz',
  'name': 'Collisions16_UltraLegacy_goldenJSON'},
 '2017': {'file': '/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2017_UL/puWeights.json.gz',
  'name': 'Collisions17_UltraLegacy_goldenJSON'},
 '2018': {'file': '/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2018_UL/puWeights.json.gz',
  'name': 'Collisions18_UltraLegacy_goldenJSON'}}

In [3]:
f = gzip.open(pileupJSONfiles['2018']['file'])
f

<gzip _io.BufferedReader name='/cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/LUM/2018_UL/puWeights.json.gz' 0x7f80f9842d90>

In [4]:
lines = f.readlines()

In [5]:
lines[0]

b'{"schema_version": 2, "corrections": [{"name": "Collisions18_UltraLegacy_goldenJSON", "version": 0, "inputs": [{"name": "NumTrueInteractions", "type": "real", "description": "Number of true interactions"}, {"name": "weights", "type": "string", "description": "nominal, up, or down"}], "output": {"name": "weight", "type": "real", "description": "Event weight for pileup reweighting"}, "data": {"nodetype": "category", "input": "weights", "content": [{"key": "nominal", "value": {"nodetype": "binning", "input": "NumTrueInteractions", "flow": "clamp", "edges": [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.

In [6]:
puWeightsJSON = correctionlib.CorrectionSet.from_file(pileupJSONfiles['2018']['file'])
puWeightsJSON

In [7]:
corr = puWeightsJSON['Collisions18_UltraLegacy_goldenJSON']
corr

In [8]:
corr.evaluate(99., 'nominal')

1.0

In [9]:
corr.evaluate([99., 99., 99.], 'nominal')

RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

In [10]:
corr.evaluate(np.array([99., 99., 99.]), 'nominal')

array([1., 1., 1.])

In [11]:
filename = "/pnfs/psi.ch/cms/trivcat/store/user/mmarcheg/RunIIFall17NanoAODv7/ttHTobb_M125_TuneCP5_13TeV-powheg-pythia8/587E2464-42CA-3A45-BD49-D23E49F658E6.root"
#events = NanoEventsFactory.from_root(filename, schemaclass=NanoAODSchema).events()
events = NanoEventsFactory.from_root(filename, schemaclass=NanoAODSchema, entry_stop=100).events()

In [12]:
events.Pileup.nPU

<Array [27, 13, 20, 14, 23, ... 26, 44, 28, 12] type='100 * int32[parameters={"_...'>

In [13]:
type(events.Pileup.nPU)

awkward.highlevel.Array

In [14]:
corr.evaluate(events.Pileup.nPU.to_numpy(), 'nominal')

array([0.98128914, 0.80678134, 0.94641737, 0.83239376, 0.99084239,
       0.98016382, 0.98016382, 0.98016382, 1.08183655, 1.19963881,
       0.99822759, 1.02087936, 0.98688717, 0.98128914, 1.0051285 ,
       1.17696172, 1.00662441, 1.03718   , 1.12598724, 1.03718   ,
       1.00338579, 0.97978296, 0.99286314, 0.97978296, 0.98128914,
       0.99084239, 1.00662441, 0.63088226, 0.98016382, 1.00175757,
       1.07108805, 0.97978296, 1.20947461, 0.88210136, 1.10982112,
       0.9664075 , 0.9925997 , 0.91870999, 0.97978296, 1.09509999,
       1.00338579, 0.99822759, 1.12598724, 0.98128914, 1.00883794,
       1.02818737, 0.9925997 , 1.19157705, 0.97978296, 0.91870999,
       1.0051285 , 1.07108805, 1.12598724, 1.14247509, 1.00338579,
       0.98016382, 1.10982112, 1.03718   , 0.9925997 , 0.94641737,
       0.9925997 , 1.16807473, 1.19722495, 0.99822759, 0.87251027,
       0.99286314, 0.85640639, 1.0051285 , 0.87251027, 1.03718   ,
       0.83239376, 1.02087936, 1.01166006, 1.15474817, 0.98016

In [15]:
corr.evaluate(events.Pileup.nPU.to_numpy(), 'up')

array([0.90737963, 0.64106782, 0.7958842 , 0.66177931, 0.88635566,
       0.86012354, 0.86012354, 0.86012354, 1.37517754, 2.38741387,
       0.92589272, 1.03670031, 0.91337014, 0.90737963, 0.94576325,
       2.14202738, 0.95562331, 1.11689768, 1.6679223 , 1.11689768,
       0.93785349, 0.90373232, 0.91952749, 0.90373232, 0.90737963,
       0.88635566, 0.95562331, 2.45572841, 0.86012354, 0.93192481,
       1.29947274, 0.90373232, 2.77156037, 0.71025075, 1.55988088,
       0.83003808, 0.90131464, 0.7584186 , 0.90373232, 1.46231542,
       0.93785349, 0.92589272, 1.6679223 , 0.90737963, 0.96882741,
       1.07280686, 0.90131464, 2.64536577, 0.90373232, 0.7584186 ,
       0.94576325, 1.29947274, 1.6679223 , 1.7843951 , 0.93785349,
       0.86012354, 1.55988088, 1.11689768, 0.90131464, 0.7958842 ,
       0.90131464, 2.02391189, 2.47876362, 0.92589272, 0.69786414,
       0.91952749, 0.68231789, 0.94576325, 0.69786414, 1.11689768,
       0.66177931, 1.03670031, 0.98594167, 1.90086069, 0.86012

In [16]:
corr.evaluate(events.Pileup.nPU.to_numpy(), 'down')

array([1.06397114, 1.02629522, 1.11057554, 1.0569706 , 1.09465062,
       1.10023745, 1.10023745, 1.10023745, 0.75298655, 0.52883855,
       1.07457281, 0.9504741 , 1.06901878, 1.06397114, 1.05423152,
       0.56197304, 1.04037516, 0.88969699, 0.65914636, 0.88969699,
       1.06438736, 1.06318451, 1.07312276, 1.06318451, 1.06397114,
       1.09465062, 1.04037516, 0.12550681, 1.10023745, 1.07175895,
       0.7886988 , 1.06318451, 0.46340916, 1.09718602, 0.68804118,
       1.10767668, 1.08535479, 1.10318463, 1.06318451, 0.71949398,
       1.06438736, 1.07457281, 0.65914636, 1.06397114, 1.02324389,
       0.92099687, 1.08535479, 0.47331664, 1.06318451, 1.10318463,
       1.05423152, 0.7886988 , 0.65914636, 0.63260127, 1.06438736,
       1.10023745, 0.68804118, 0.88969699, 1.08535479, 1.11057554,
       1.08535479, 0.58376889, 0.50934332, 1.07457281, 1.09675594,
       1.07312276, 1.08351634, 1.05423152, 1.09675594, 0.88969699,
       1.0569706 , 0.9504741 , 1.00230337, 0.60641076, 1.10023